### PR TITLE
settings for deploy-heroku steps

### PR DESCRIPTION
**Pull request by gonzalez-aj**
- I'm at about 7 minutes into the tutorial
- https://github.com/nashville-software-school/server-side-python-curriculum/blob/evening-cohorts/book-4-bangazon/chapters/HEROKU_DEPLOYMENT.md
- so I'm stuck at the automatic deploy setup
- hannah's video, she included pipfile.lock in the repo, but we have ours in the .gitignore file

### CODE REVIEW

**Review by gonzalez-aj — COMMENTED** [review]
**### _*HEROKU DEPLOY SUCCESS*_** WHY DID I HAVE TO RE-INSTALL CLOUDINARY???  :D

**Comment by gonzalez-aj** [comment]
i did NOT run `touch rest_framework/css/bootstrap.min.css.map rest_framework/css/bootstrap-theme.min.css.map`

**Review by gonzalez-aj — COMMENTED** [review]
STATIC_URL was already in the file so I removed the redundancy.

**Review by ericlfrey — APPROVED** [review]
I would just comment out the pipfile in the gitignore and continue with her video. Great going!

**Pull request merged**
